#!/bin/bash

cd /home/isak/Documents/Master/
git clone https://github.com/facebook/react-native
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
git clone 
