#!/bin/bash
#Do a historical merge again to analyze the conflict
#$1: repo
#$2: left ancestral commit
#$3: right ancestral commit
#$4: branch name to use

cd $1

git reset --hard $2
git clean -f
git branch $4
git checkout $3
git merge $4
